language: generic

services:
 - docker

env:
 - DEPENDENCY_PACKAGES="libcanberra-gtk3-dev libgranite-dev libglib2.0-dev libgtk-3-dev libnotify-dev libpulse-dev libwingpanel-2.0-dev libxml2-utils meson valac"

install:
 - docker pull elementary/docker:juno-unstable
 - docker run -v "$PWD":/tmp/build-dir elementary/docker:juno-unstable /bin/sh -c "apt-get update && apt-get -y install $DEPENDENCY_PACKAGES && cd /tmp/build-dir && meson build --prefix=/usr && cd build && ninja test"
 - docker pull elementary/docker:juno-unstable
 - docker run -v "$PWD":/tmp/build-dir elementary/docker:juno-unstable /bin/sh -c "apt-get update && apt-get -y install $DEPENDENCY_PACKAGES && cd /tmp/build-dir && rm -rf build && meson build --prefix=/usr && cd build && ninja test"

script:
- echo BUILDS PASSED
